### ISSUE TITLE
Hosted instance of DBpedia Spotlight

### ISSUE THREAD

**Issue by jeanqussa** [ude-soco/CourseMapper-webserver#1008]
The API service for DBpedia Spotlight (https://api.dbpedia-spotlight.org) has been down for some time. Would it be possible to host our own instance?

I have come up with the following docker-compose configuration that works on my machine:

```
  dbpedia-spotlight:
    image: dbpedia/dbpedia-spotlight
    volumes:
      - dbpedia-spotlight-model:/opt/spotlight
    deploy:
      resources:
        limits:
          memory: 10G
    command: spotlight.sh en
```

We would only need 1 hosted instance of DBpedia Spotlight, and it needs to be exposed to the internet so that both the CourseMapper deployments and end users running the project locally can access it.
