### ISSUE TITLE
AWS access key required

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/CourseMapper-webserver#1041]
@jeanqussa The following hard-coded values need to be replaced:

```yaml
services:
  wp-pg:
    environment:
      ACCESS_KEY_ID: ACCESS_KEY_ID
      SECRET_ACCESS_KEY: SECRET_ACCESS_KEY
```

Please send me the appropriate values for production.
